<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQWfBzRb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQWfBzRb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQWfBzRb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQWfBzRb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQWfBzRb\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'QWfBzRb',
    'container.build_id' => '333d409c',
    'container.build_time' => 1546508576,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQWfBzRb');
