<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Wgfmtm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Wgfmtm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Wgfmtm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Wgfmtm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5Wgfmtm\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '5Wgfmtm',
    'container.build_id' => 'c071f9c8',
    'container.build_time' => 1546506462,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5Wgfmtm');
