<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWAJtAeh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWAJtAeh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWAJtAeh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWAJtAeh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWAJtAeh\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'WAJtAeh',
    'container.build_id' => '2c52edc9',
    'container.build_time' => 1546505009,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWAJtAeh');
